engines:
  shellcheck:
    enabled: true
    checks:
      SC2034:
        enabled: false
      SC2154:
        enabled: false
      SC2162:
        enabled: false

ratings:
   paths:
     - "SOURCES/rpmbuilder"
     - "SOURCES/rpmunbuilder"
     - "SOURCES/buildmon"
