language: bash

sudo: required

services:
  - docker

matrix:
  fast_finish: true

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
  - tar xf shellcheck-latest.linux.x86_64.tar.xz
  - ./shellcheck-latest/shellcheck --version
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - chmod +x perfecto-docker

script:
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/rpmbuilder SOURCES/libexec/*.shx'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/rpmunbuilder'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/buildmon'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/initenv'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/nodeinfo'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/docker-entrypoint'
 - ./perfecto-docker rpmbuilder.spec
 - ./perfecto-docker rpmbuilder-node.spec
