language: generic

sudo: required

services:
  - docker

matrix:
  fast_finish: true

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
  - wget -O hadolint "https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64"
  - tar xf shellcheck-stable.linux.x86_64.tar.xz
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - chmod +x perfecto-docker
  - chmod +x hadolint
  - ./perfecto-docker --version
  - ./shellcheck-stable/shellcheck --version
  - ./hadolint --version

script:
 - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck SOURCES/rpmbuilder SOURCES/libexec/*.shx'
 - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck SOURCES/rpmunbuilder'
 - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck SOURCES/buildmon'
 - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck SOURCES/initenv'
 - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck SOURCES/nodeinfo'
 - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck SOURCES/docker-entrypoint'
 - ./perfecto-docker rpmbuilder.spec
 - ./perfecto-docker rpmbuilder-node.spec
 - ./hadolint centos6.docker
 - ./hadolint centos7.docker
