language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script:
 - bash -c 'shopt -s globstar; shellcheck SOURCES/rpmbuilder SOURCES/libexec/*.shx'
 - bash -c 'shopt -s globstar; shellcheck SOURCES/rpmunbuilder'
 - bash -c 'shopt -s globstar; shellcheck SOURCES/buildmon'
 - bash -c 'shopt -s globstar; shellcheck SOURCES/initenv'
 - bash -c 'shopt -s globstar; shellcheck SOURCES/nodeinfo'

matrix:
  fast_finish: true
