language: bash

sudo: false

before_install:
  - make get-shellcheck

script:
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/rpmbuilder SOURCES/libexec/*.shx'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/rpmunbuilder'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/buildmon'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/initenv'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/nodeinfo'

matrix:
  fast_finish: true
