#!/usr/bin/env bash

###############################################################################

APP="RPMBuilder Node Monitor"
VER="1.1.2"

###############################################################################

BUILDER_USER="builder"
BUILDER_DIR="/home/builder"
EXEC="$BUILDER_DIR/buildmon"
BUILD_LOCK="$BUILDER_DIR/.buildlock"
CLEAN_PERIOD=600 # 10 Min
MAX_KEEP_DAYS=7 # 1 Week
DIR_LIST="BUILD BUILDROOT RPMS SOURCES SPECS SRPMS"

CWD=$(pwd)

###############################################################################

main() {
  trap doExit SIGINT SIGTERM

  check

  doExit
}

check() {
  local counter=0

  while : ; do
    sleep 3

    if isBuildInProgress ; then
      touch $BUILD_LOCK
    else
      if [[ -e $BUILD_LOCK ]] ; then
        rm -f $BUILD_LOCK
      fi
    fi

    ((counter++))

    if [[ $counter -gt $CLEAN_PERIOD ]] ; then
      counter=0
      clean
    fi
  done
}

isBuildInProgress() {
  if [[ $(pgrep -U "$BUILDER_USER" "rpmbuild") ]] ; then
    return 0
  fi

  if [[ $(pgrep -U "$BUILDER_USER" "yum-builddep") ]] ; then
    return 0
  fi

  return 1
}

clean() {
  for dir in $DIR_LIST ; do
    find "$BUILDER_DIR/rpmbuild/$dir" -maxdepth 1 -mtime +$MAX_KEEP_DAYS -delete
  done
}

doExit() {
  rm -f $BUILD_LOCK
  exit 0
}

###############################################################################

main "$0"
