#!/usr/bin/env bash

###############################################################################

APP="RPMBuilder Node Monitor"
VER="1.1.0"

###############################################################################

BUILDER_USER="builder"
BUILDER_DIR="/home/builder"
EXEC="$BUILDER_DIR/buildmon"
BUILD_LOCK="$BUILDER_DIR/.buildlock"
CLEAN_DELAY=600
KEEP_DAYS=7 # 1 Week
DIR_LIST="BUILD BUILDROOT RPMS SOURCES SPECS SRPMS"

CWD=$(pwd)

###############################################################################

main() {
  trap doExit SIGINT SIGTERM
  check
  doExit
}

check() {
  local has_lock
  local dl

  dl=0

  while : ; do
    sleep 1

    if [[ $(pgrep -U $BUILDER_USER rpmbuild) ]] ; then
      touch $BUILD_LOCK
      has_lock=true
    else
      if [[ $has_lock ]] ; then
        rm -f $BUILD_LOCK
        has_lock=""
      fi
    fi

    ((dl++))

    if [[ $dl -eq $CLEAN_DELAY ]] ; then
      dl=0 ; clean
    fi
  done
}

clean() {
  local rbdir="$BUILDER_DIR/rpmbuild"
  find $rbdir -maxdepth 1 -type d -mtime +$KEEP_DAYS -delete
}

doExit() {
  rm -f "$BUILD_LOCK"
  exit 0
}

###############################################################################

main "$0"
