#!/usr/bin/env bash
# shellcheck disable=SC1117,SC2034,SC2154

########################################################################################

APP="RPMUnbuilder"
VER="1.1.5"

########################################################################################

NORM=0
BOLD=1
UNLN=4
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAG=35
CYAN=36
GREY=37
DARK=90

CL_NORM="\e[0m"
CL_BOLD="\e[0;${BOLD};49m"
CL_UNLN="\e[0;${UNLN};49m"
CL_RED="\e[0;${RED};49m"
CL_GREEN="\e[0;${GREEN};49m"
CL_YELLOW="\e[0;${YELLOW};49m"
CL_BLUE="\e[0;${BLUE};49m"
CL_MAG="\e[0;${MAG};49m"
CL_CYAN="\e[0;${CYAN};49m"
CL_GREY="\e[0;${GREY};49m"
CL_DARK="\e[0;${DARK};49m"
CL_BL_RED="\e[1;${RED};49m"
CL_BL_GREEN="\e[1;${GREEN};49m"
CL_BL_YELLOW="\e[1;${YELLOW};49m"
CL_BL_BLUE="\e[1;${BLUE};49m"
CL_BL_MAG="\e[1;${MAG};49m"
CL_BL_CYAN="\e[1;${CYAN};49m"
CL_BL_GREY="\e[1;${GREY};49m"

SUPPORTED_ARGS="help usage ver version"
SHORT_ARGS="h:help v:version"

########################################################################################

main() {
  if [[ -n "$ver" || -n "$version" ]] ; then
    about
    exit 0
  fi

  if [[ $# -eq 0 || -n "$help" || -n "$usage" ]] ; then
    usage
    exit 0
  fi

  if [[ ! $(checkDeps "rpm" "rpm2cpio" "cpio") ]] ; then
    error "For using this utility install this packages first: rpm rpm2cpio cpio"
    exit 2
  fi

  local pkg="$1"
  local path="$2"

  if [[ ! $(isRPMPackage "$pkg") ]] ; then
    error "Error! [$pkg] is not an rpm package!"
    exit 1
  fi

  if [[ -n "$path" ]] ; then
    if [[ ! $(checkPerms "$path" "DWX") ]] ; then
      error "Error! Please check permissions for directory [$path]."
      exit 3
    fi
  else
    path=$(pwd)

    if [[ ! $(checkPerms "$path" "DWX") ]] ; then
      error "Error! Please check permissions for directory [$path]."
      exit 3
    fi
  fi

  processPackage "$pkg" "$path"
}

processPackage() {
  local pkg="$1"
  local path="$2"

  showm "Unbuilding package: " $BOLD

  local src_name src_list

  src_list=$(rpm2cpio "$pkg" | cpio -div --quiet 2>&1 | grep -v "cpio:")

  mkdir -p "$path/SOURCES"

  for src_name in $src_list ; do
    if [[ $src_name =~ .spec ]] ; then
      mv "$src_name" "$path" &> /dev/null
    else
      mv "$src_name" "$path/SOURCES" &> /dev/null
    fi
  done

  show "DONE" $GREEN
}

isRPMPackage() {
  

  if LC_ALL=C rpm -qp --qf "%{name}\n" "$1" &> /dev/null ; then
    echo 1 && return 0
  else
    echo "" && return 1
  fi
}

checkPerms() {
  local path="$1"
  local perms

  perms=$(echo "$2" | tr "[:lower:]" "[:upper:]")

  for perm in $(echo "$perms" | fold -w1) ; do
    case $perm in
      "R") [[ ! -r $path ]] && echo "" && return 1 ;;
      "W") [[ ! -w $path ]] && echo "" && return 1 ;;
      "E") [[ ! -e $path ]] && echo "" && return 1 ;;
      "D") [[ ! -d $path ]] && echo "" && return 1 ;;
      "F") [[ ! -f $path ]] && echo "" && return 1 ;;
      "S") [[ ! -s $path ]] && echo "" && return 1 ;;
      "H") [[ ! -h $path ]] && echo "" && return 1 ;;
      "X") [[ ! -x $path ]] && echo "" && return 1 ;;
      *) echo "" && return 1
    esac
  done

  echo 1
  return 0
}

####################################################################

checkDeps() {
  for app in "$@" ; do
    type -P "$app" &> /dev/null

    if [[ $? -eq 1 ]] ; then
      echo ""
      return 1
    fi
  done

  echo 1
  return 0
}

show() {
  if [[ -n "$2" ]] ; then
    echo -e "\e[${2}m${1}\e[0m"
  else
    echo -e "$*"
  fi
}

showm() {
  if [[ -n "$2" ]] ; then
    echo -e -n "\e[${2}m${1}\e[0m"
  else
    echo -e -n "$*"
  fi
}

error() {
  show "$@" $RED 1>&2
}

showArgWarn() {
  error "Error! Unknown argument $1."
  doExit 1
}

usage() {
  show "${CL_BOLD}Usage:${CL_NORM} rpmunbuilder ${CL_BROWN}{rpm-file}${CL_NORM} ${CL_GREEN}{path}${CL_NORM}"
}

about() {
  show "${CL_BL_CYAN}$APP${CL_NORM} ${CL_CYAN}$VER${CL_NORM} - Source RPM unbuilder"
  show ""
  show "Copyright (C) 2009-$(date +%Y) ESSENTIAL KAOS" $DARK
  show "Essential Kaos Open Source License <https://essentialkaos.com/ekol>" $DARK
}

## ARGUMENTS PARSING 3 #################################################################

[[ $# -eq 0 ]] && main && exit $?

unset arg argn argm argv argt argk

argv="$*" ; argt=""

while [[ -n "$1" ]] ; do
  if [[ "$1" =~ \  && -n "$argn" ]] ; then
    declare "$argn=$1"

    unset argn && shift && continue
  elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
    argm=${1:1}

    if [[ \ $SHORT_ARGS\  =~ \ $argm:!?([a-zA-Z0-9_]*) ]] ; then
      arg="${BASH_REMATCH[1]}"
    else
      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
      shift && continue
    fi

    if [[ -z "$argn" ]] ; then
      argn=$arg
    else
      # shellcheck disable=SC2015
      [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
      argn=$arg
    fi

    if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
      shift && continue
    fi

    if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
      declare "$argn=true" ; unset argn ; argk=true
    else
      unset argk
    fi

    shift && continue
  elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
    arg=${1:2}

    if [[ $arg == *=* ]] ; then
      IFS="=" read -ra arg <<< "$arg"

      argm="${arg[0]}" ; argm=${argm//-/_}

      if [[ ! $SUPPORTED_ARGS\  =~ $argm\  ]] ; then
        declare -F showArgWarn &>/dev/null && showArgWarn "--${arg[0]//_/-}"
        shift && continue
      fi

      # shellcheck disable=SC2015
      [[ -n "${!argm}" && $MERGEABLE_ARGS\  =~ $argm\  ]] && declare "$argm=${!argm} ${arg[*]:1:99}" || declare "$argm=${arg[*]:1:99}"

      unset argm && shift && continue
    else
      arg=${arg//-/_}

      if [[ -z "$argn" ]] ; then
        argn=$arg
      else
        # shellcheck disable=SC2015
        [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
        argn=$arg
      fi

      if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
        declare -F showArgWarn &>/dev/null && showArgWarn "--${argn//_/-}"
        shift && continue
      fi

      if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
        declare "$argn=true" ; unset argn ; argk=true
      else
        unset argk
      fi

      shift && continue
    fi
  else
    if [[ -n "$argn" ]] ; then
      # shellcheck disable=SC2015
      [[ -n "${!argn}" && $MERGEABLE_ARGS\  =~ $argn\  ]] && declare "$argn=${!argn} $1" || declare "$argn=$1"

      unset argn && shift && continue
    fi
  fi

  argt="$argt $1" ; shift

done

[[ -n "$argn" ]] && declare "$argn=true"

unset arg argn argm argk

# shellcheck disable=SC2015,SC2086
[[ -n "$KEEP_ARGS" ]] && main $argv || main ${argt:1:9999}

########################################################################################
