#!/usr/bin/env bash

set -e

chmod 777 /dev/stdout

user_id=${LOCAL_USER_ID:-9001}

# Create builder user
useradd -s /bin/bash -u "$user_id" -M -d /home/builder builder

# Generate password for superuser
su_pass=$(pwgen -sB1 18)

# Update superuser password
echo "$su_pass" | passwd root --stdin &> /dev/null

# Save superuser password into file
echo "$su_pass" > /home/builder/superuser.txt
chmod 400 /home/builder/superuser.txt

# Change permissions for builder files and directories
chown -R builder:builder /home/builder

exec /usr/local/bin/gosu builder "$@"
