#!/usr/bin/env bash
# shellcheck disable=SC2269

set -e

if [[ -z "$PUB_KEY" ]] ; then
  echo "Public key is not set" 1>&2
  exit 1
fi

USER_ID=9001

chmod 777 /dev/stdout

# Create builder user
useradd -s /bin/bash -u "$USER_ID" -M -d /home/builder builder

# Unlock user account
passwd -fu builder

# Export public key to authorized_keys file
echo "$PUB_KEY" > /home/builder/.ssh/authorized_keys

# Export proxy configuration
if [[ -n "$http_proxy" || -n "$HTTP_PROXY" ]] ; then
  cat < EOF >> /etc/environment
HTTP_PROXY=${HTTP_PROXY:-$http_proxy}
http_proxy=${http_proxy:-$HTTP_PROXY}
HTTPS_PROXY=${HTTPS_PROXY:-$https_proxy}
https_proxy=${https_proxy:-$HTTPS_PROXY}
no_proxy=$no_proxy
EOF
fi

# Change permissions for builder files and directories
chown -R builder:builder /home/builder

# Generate host keys
ssh-keygen -A &> /dev/null

# Start SSH daemon
/usr/sbin/sshd -D -p "${SSH_PORT:-2022}" -E /var/log/secure
