name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check specs with Perfecto
        uses: essentialkaos/perfecto-action@v2
        with:
          files: rpmbuilder.spec rpmbuilder-node.spec

  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check scripts with Shellcheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: SOURCES/rpmbuilder SOURCES/libexec/*.shx SOURCES/rpmunbuilder SOURCES/buildmon SOURCES/initenv SOURCES/nodeinfo .docker/entrypoint .docker/node-entrypoint rpmbuilder-docker

  Hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check dockerfiles with Hadolint
        uses: essentialkaos/hadolint-action@v1
        with:
          files: .docker/centos7.docker .docker/ol7.docker .docker/ol8.docker .docker/ol9.docker .docker/node-centos7.docker .docker/node-ol7.docker .docker/node-ol8.docker .docker/node-ol9.docker

  DockerBuild:
    name: Docker Build Check
    runs-on: ubuntu-latest

    needs: [Hadolint, Shellcheck, Perfecto]

    env:
      REGISTRY: ghcr.io

    strategy:
      matrix:
        image: [ 'centos7', 'ol7', 'ol8', 'ol9', 'node-centos7', 'node-ol7', 'node-ol8', 'node-ol9' ]

    steps:
      - name: Check event type
        run: |
          if [[ "${{github.event_name}}" != "pull_request" ]] ; then
            echo "::notice::Event type is not 'pull_request', all job actions will be skipped"
          fi

          # This step is a hack for needs+if issue with actions
          # More info about issue: https://github.com/actions/runner/issues/491

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        if: ${{ github.event_name == 'pull_request' && env.DOCKERHUB_USERNAME != '' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker build --build-arg REGISTRY=${REGISTRY} -f .docker/${{matrix.image}}.docker -t ${{matrix.image}} .

      - name: Show info about built Docker images
        uses: essentialkaos/docker-info-action@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          image: ${{matrix.image}}
          show-labels: true
